### ISSUE TITLE
Add paragraphs needed for user testing to localgov_page

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_page#1]
@stephen-cox @ekes @markconroy @msayoung 

Coming from https://github.com/localgovdrupal/localgov_microsites/issues/67

Currently we are just using this content type in the localgov_microsites distribution, not in the main distribution. Longer term it will probably be useful there too.

In the immediate term, we need a reasonable range of paragraphs to test this with when we do user testing next week.

They are enabled on https://microsites.localgovdrupal.org/admin/structure/types/manage/localgov_page/fields/node.localgov_page.localgov_page_content but not yet in config, so reinstalling locally or on a test site will  take manual intervention.

So I suggest we add them here for now, with whatever dependencies that entails, so we have a content type that is working on repeated installs for our testing.

I'll create a branch of this and a PR for review and further discussion if needed, but if anyone has a better suggestion, holler!

**Comment by ekes** [comment]
I thought the point of having a database to import was to negate having to do this?

**Comment by finnlewis** [comment]
I think a database to import will help with perhaps a bunch of setup tasks when we're ready to run the testing, like maybe stubbing out some default accounts and a few more content nodes, but right now I'm reinstalling every hour or so and trying to test things, which is involving lots of pointing and clicking to get things working. I think we need to minimise this overhead.

Maybe I've misunderstood something, but why don't we want the paragraphs config in the content type for now?

**Comment by ekes** [comment]
> Maybe I've misunderstood something, but why don't we want the paragraphs config in the content type for now?

My understanding was that it's going to have to be undone and changed? If not then fine it will have to depend on some paragraphs I assume... or is this actually better is some other modules that apply their paragraphs _to_ the page?

**Comment by finnlewis** [comment]
Longer term I think we need to review where all the paragraphs are in localgov drupal, maybe move those in localgov_subsites_paragraphs to localgov_paragraphs, then we can just depend on a single paragraphs module and use those we want on a given content type. 

But for now, we are relying on paragraphs from localgov_subsites_paragraphs to give us more to test with. 

So yes, I would expect us to refactor to remove the dependency on localgov_subsites_paragraphs.

Right now I'm less bothered about where they live, I just want the paragraphs enabled out of the box to save time and ensure consistency so we can build some microsites.
