### ISSUE TITLE
Use the "secondary banner" paragraph type instead of a new banner field

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_page#15]
We're currently using a new media field for the banner on localgov_page
We _could_/_should_ use the secondary banner paragraph we already have in subsites (soon to move to localgov_paragraphs)

**Comment by msayoung** [comment]
@markconroy remind me why this is a good idea (for the record)

**Comment by msayoung** [comment]
We're going to need to faff about more with the labels , otherwise we have this which isn't ideal as we're not using the _banner primary_

![Image](https://user-images.githubusercontent.com/3852805/176445514-94be0f5d-9a37-4d3f-8776-7161f73c0617.png)

**Comment by markconroy** [comment]
It means we can add a field for "Image style", but also means site can add more/other fields if they wanted to it. At the moment with just an image field, there's very little you can do, especially if (God forbid) someone wanted a slider that has image + text + XYZ.

It also means any updates we deploy to the banner paragraph type in the future will automatically be available to this field.

**Comment by markconroy** [comment]
P.S. I don't think we should use _just_ the banner secondary, let's use both - like we do with subsites.

**Comment by msayoung** [comment]
> P.S. I don't think we should use _just_ the banner secondary, let's use both - like we do with subsites.

! 

Lets put that the backlog. I can see the rationale, but might sense check what's there first.
