### ISSUE TITLE
Allow the summary field to be optionally displayed

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_page#32]
Users reported that sometimes they dont want the summary field to display on a Page. 
They were happy to fill it in for metatag purposes (if this is how its used) but would like to be able to optionally turn it off.

**Comment by finnlewis** [comment]
@markconroy suggests maybe hook_preprocess_node to check value and unset the in some case.

This is just on the full content display. 

So: 

- [x] add a checkbox next to the summary field "Hide summary on page view" (default unchecked) 
- [x] add some hook_preprocess_node or something to work the magic

@ekes do we need an automated test for this.
